# Generated by Django 2.2.7 on 2019-12-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('u', 'Blue'), ('r', 'Red'), ('y', 'Yellow'), ('p', 'Purple'), ('o', 'Orange'), ('g', 'Green'), ('n', 'Brown'), ('w', 'White'), ('b', 'Black'), ('s', 'Silver')], default='b', max_length=20),
        ),
    ]
