# Generated by Django 2.2.7 on 2019-12-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0005_auto_20191202_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='stuff',
            field=models.ManyToManyField(to='eCommerce.Product'),
        ),
    ]
