# Generated by Django 2.2.7 on 2019-12-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0006_lists_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='location',
            field=models.CharField(choices=[('wish list', 'wish list'), ('shopping cart', 'shopping cart')], default='wish list', max_length=5),
        ),
    ]
