# Generated by Django 2.2.7 on 2019-12-03 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eCommerce', '0008_auto_20191202_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.FloatField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank='true', choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], null='true')),
                ('text', models.TextField(blank='true', null='true')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCommerce.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
