# Generated by Django 2.2.7 on 2019-12-04 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0010_auto_20191203_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='username',
        ),
    ]
