# Generated by Django 2.2.7 on 2019-12-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0011_auto_20191204_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='reviewUser',
        ),
    ]
