# Generated by Django 2.2.7 on 2019-12-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0012_auto_20191204_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewUser',
            new_name='reviewer',
        ),
    ]
