# Generated by Django 2.2.7 on 2019-12-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0013_auto_20191204_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.CharField(blank='true', max_length=200, null='true'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.CharField(blank='true', max_length=200, null='true'),
        ),
    ]
