# Generated by Django 2.2.7 on 2019-12-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0016_auto_20191204_0716'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
