# Generated by Django 2.2.7 on 2019-12-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0020_auto_20191204_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(blank='true', max_length=200, null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='review',
            name='number',
            field=models.PositiveSmallIntegerField(blank='true', choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], null='true'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.CharField(blank='true', max_length=200, null='true'),
        ),
    ]
