# Generated by Django 2.2.7 on 2019-12-04 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0021_auto_20191204_0737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
