# Generated by Django 2.2.7 on 2019-12-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0024_auto_20191204_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='stuff',
        ),
        migrations.AddField(
            model_name='cart',
            name='stuff',
            field=models.CharField(blank='true', max_length=200, null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.CharField(blank='true', max_length=200, null='true'),
        ),
        migrations.RemoveField(
            model_name='wish',
            name='stuff',
        ),
        migrations.AddField(
            model_name='wish',
            name='stuff',
            field=models.CharField(blank='true', max_length=200, null='true'),
            preserve_default='true',
        ),
    ]
